# Generated by Django 4.2.7 on 2023-11-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PolwroMED', '0002_lekarz_pacjent_gabinet_wizyta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizyta',
            name='czas_wizyty',
        ),
        migrations.RemoveField(
            model_name='wizyta',
            name='data_wizyty',
        ),
        migrations.AddField(
            model_name='gabinet',
            name='lekarze',
            field=models.ManyToManyField(related_name='gabinety_lekarzy', to='PolwroMED.lekarz'),
        ),
        migrations.AddField(
            model_name='lekarz',
            name='gabinety',
            field=models.ManyToManyField(related_name='lekarze_gabinetow', to='PolwroMED.gabinet'),
        ),
        migrations.AddField(
            model_name='wizyta',
            name='gabinet',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='PolwroMED.gabinet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gabinet',
            name='numer_gabinetu',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='diagnoza',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='notatki_lekarza',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='przepisane_leki',
            field=models.TextField(blank=True),
        ),
    ]
