# Generated by Django 4.2.7 on 2023-11-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PolwroMED', '0004_remove_pacjent_inne_informacje'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacjent',
            name='inne_informacje',
            field=models.TextField(default='1', max_length=3000),
            preserve_default=False,
        ),
    ]
