# Generated by Django 4.2.7 on 2023-11-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PolwroMED', '0005_pacjent_inne_informacje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gabinet',
            name='lekarz',
        ),
        migrations.AlterField(
            model_name='gabinet',
            name='lekarze',
            field=models.ManyToManyField(blank=True, related_name='gabinety_lekarzy', to='PolwroMED.lekarz'),
        ),
    ]
