# Generated by Django 4.2.7 on 2023-11-30 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PolwroMED', '0006_remove_gabinet_lekarz_alter_gabinet_lekarze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='pesel',
            field=models.IntegerField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=11, message='PESEL musi mieć dokładnie 11 cyfr.'), django.core.validators.MaxLengthValidator(limit_value=11, message='PESEL musi mieć dokładnie 11 cyfr.')]),
        ),
    ]
