# Generated by Django 4.2.7 on 2023-11-30 18:29

import PolwroMED.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PolwroMED', '0007_alter_pacjent_pesel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='data_urodzenia',
            field=models.DateField(validators=[PolwroMED.models.validate_birthdate, PolwroMED.models.validate_age]),
        ),
    ]
