# Generated by Django 4.2.7 on 2023-11-30 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PolwroMED', '0008_alter_pacjent_data_urodzenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='pesel',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=11, message='PESEL musi mieć dokładnie 11 cyfr.'), django.core.validators.MaxLengthValidator(limit_value=11, message='PESEL musi mieć dokładnie 11 cyfr.'), django.core.validators.RegexValidator(message='PESEL może zawierać tylko cyfry.', regex='^\\d*$')]),
        ),
    ]
