# Generated by Django 5.0 on 2023-12-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PolwroMED', '0009_alter_pacjent_pesel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='inne_informacje',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
