# Generated by Django 4.2.7 on 2024-01-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PolwroMED', '0012_lekarz_godziny_pracy_koniec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyta',
            name='status',
            field=models.CharField(choices=[('zaplanowana', 'Zaplanowana'), ('odbyta', 'Odbyta'), ('anulowana', 'Anulowana'), ('wolna', 'Wolna')], default='wolna', max_length=20),
        ),
    ]
