# Generated by Django 4.2.7 on 2024-01-06 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PolwroMED', '0013_alter_wizyta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacjent', to=settings.AUTH_USER_MODEL),
        ),
    ]
